apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::740361887714:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-qgjPm5iCQorg
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
        - system:masters
      rolearn: arn:aws:iam::740361887714:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-17T13:13:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1297"
  uid: 7c8dd9a1-c766-47b4-acd5-07641624d2f5